# Generated by Django 5.1.3 on 2024-12-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_cinema_cart_hall_screening_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.cart', verbose_name='Корзина'),
        ),
    ]
