# Generated by Django 5.1.3 on 2024-12-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_seat_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Место забронировано'),
        ),
    ]
