# Generated by Django 5.1.3 on 2024-12-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_seat_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='films.cinema', verbose_name='Кинотеатр'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='films.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='films.cart', verbose_name='Корзина'),
        ),
    ]
